{{- if .Values.secrets.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "app.fullname" . }}
  labels:
    {{- include "app.labels" . | nindent 4 }}
stringData:
  {{- toYaml .Values.secrets.stringData | nindent 2 }}
{{- end }}
